export const Data = [
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/BTmvfzDPZKJ0Zt",
    id: "1368",
    name: "ankle circles",
    target: "calves",
    secondaryMuscles: ["ankle stabilizers"],
    instructions: [
      "Sit on the ground with your legs extended in front of you.",
      "Lift one leg off the ground and rotate your ankle in a circular motion.",
      "Perform the desired number of circles in one direction, then switch to the other direction.",
      "Repeat with the other leg.",
    ],
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/s2t4Ph-WU8TSN-",
    id: "3293",
    name: "archer pull up",
    target: "lats",
    secondaryMuscles: ["biceps", "forearms"],
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/RnE24efMeL2PpC",
    id: "3294",
    name: "archer push up",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders", "core"],
    instructions: [
      "Start in a push-up position with your hands slightly wider than shoulder-width apart.",
      "Extend one arm straight out to the side, parallel to the ground.",
      "Lower your body by bending your elbows, keeping your back straight and core engaged.",
      "Push back up to the starting position.",
      "Repeat on the other side, extending the opposite arm out to the side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/uYLhxglK2SUt2c",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
    target: "abs",
    secondaryMuscles: ["shoulders", "back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your knees bent at a 90-degree angle.",
      "Engage your core and lift your knees towards your chest, bringing them as close to your elbows as possible.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/vxllktV-bpvAwP",
    id: "2333",
    name: "arm slingers hanging straight legs",
    target: "abs",
    secondaryMuscles: ["shoulders", "back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your legs straight down.",
      "Engage your core and lift your legs up in front of you until they are parallel to the ground.",
      "Hold for a moment at the top, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/NslXMEpugRMnNU",
    id: "3214",
    name: "arms apart circular toe touch (male)",
    target: "glutes",
    secondaryMuscles: ["hamstrings", "quadriceps", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart and arms extended to the sides.",
      "Keeping your legs straight, bend forward at the waist and reach down towards your toes with your right hand.",
      "As you reach down, simultaneously lift your left leg straight up behind you, maintaining balance.",
      "Return to the starting position and repeat the movement with your left hand reaching towards your toes and your right leg lifting up behind you.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/RIyrqNdFD47Hfp",
    id: "3204",
    name: "arms overhead full sit-up (male)",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms overhead, keeping them straight.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is upright.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/jr7jJcSnnSunpK",
    id: "0009",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/RCzS4PvAsFhvpg",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
      "Pause for a moment at the top of the movement, squeezing your abs.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/nByLQ3vc02kNbl",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
];

export const Target = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/t9wSVdpBuonMel",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Place your hands behind your head with your elbows pointing outwards.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/jQ8eSoiNcflP0X",
    id: "0002",
    name: "45° side bend",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Stand with your feet shoulder-width apart and your arms extended straight down by your sides.",
      "Keeping your back straight and your core engaged, slowly bend your torso to one side, lowering your hand towards your knee.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat on the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/5aan1R4IyZHaST",
    id: "0003",
    name: "air bike",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Lie flat on your back with your hands placed behind your head.",
      "Lift your legs off the ground and bend your knees at a 90-degree angle.",
      "Bring your right elbow towards your left knee while simultaneously straightening your right leg.",
      "Return to the starting position and repeat the movement on the opposite side, bringing your left elbow towards your right knee while straightening your left leg.",
      "Continue alternating sides in a pedaling motion for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/jsWi72sAuE652i",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms straight out to the sides, parallel to the ground.",
      "Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.",
      "Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/nyLlbfNw1Riljp",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
    target: "abs",
    secondaryMuscles: ["shoulders", "back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your knees bent at a 90-degree angle.",
      "Engage your core and lift your knees towards your chest, bringing them as close to your elbows as possible.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/QBzBpZfWusztXK",
    id: "2333",
    name: "arm slingers hanging straight legs",
    target: "abs",
    secondaryMuscles: ["shoulders", "back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your legs straight down.",
      "Engage your core and lift your legs up in front of you until they are parallel to the ground.",
      "Hold for a moment at the top, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/zpdWUl2RzH2WC9",
    id: "3204",
    name: "arms overhead full sit-up (male)",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms overhead, keeping them straight.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is upright.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/n8RjQ2IXfWUgoL",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
      "Pause for a moment at the top of the movement, squeezing your abs.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/0fpmQNqNsEe4aZ",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/6gpL-bHCgTBSHd",
    id: "0012",
    name: "assisted lying leg raise with lateral throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "obliques"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your abs and lift your legs off the ground, keeping them straight.",
      "While keeping your legs together, lower them to one side until they are a few inches above the ground.",
      "Pause for a moment, then lift your legs back to the starting position.",
      "Repeat the movement to the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
];

export const Equ = [
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/n8RjQ2IXfWUgoL",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
      "Pause for a moment at the top of the movement, squeezing your abs.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/0fpmQNqNsEe4aZ",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "lower legs",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/Zru5F7sjjONQRE",
    id: "1708",
    name: "assisted lying calves stretch",
    target: "calves",
    secondaryMuscles: ["hamstrings"],
    instructions: [
      "Lie on your back with your legs extended.",
      "Bend one knee and place your foot flat on the ground.",
      "Using your hands or a towel, gently pull your toes towards your body, feeling a stretch in your calf.",
      "Hold the stretch for 20-30 seconds.",
      "Release the stretch and repeat on the other leg.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/B-x5uPcsKimmY0",
    id: "1709",
    name: "assisted lying glutes stretch",
    target: "glutes",
    secondaryMuscles: ["hamstrings"],
    instructions: [
      "Lie on your back with your legs extended.",
      "Bend your right knee and place your right ankle on your left thigh, just above the knee.",
      "Grasp your left thigh with both hands and gently pull it towards your chest.",
      "Hold the stretch for 20-30 seconds.",
      "Release and repeat on the other side.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/EtmRY1YVgANK-l",
    id: "1710",
    name: "assisted lying gluteus and piriformis stretch",
    target: "glutes",
    secondaryMuscles: ["hamstrings"],
    instructions: [
      "Lie on your back with your legs extended.",
      "Bend your right knee and place your right ankle on your left thigh, just above the knee.",
      "Grasp your left thigh with both hands and gently pull it towards your chest.",
      "Hold the stretch for 20-30 seconds.",
      "Release the stretch and repeat on the other side.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/6gpL-bHCgTBSHd",
    id: "0012",
    name: "assisted lying leg raise with lateral throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "obliques"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your abs and lift your legs off the ground, keeping them straight.",
      "While keeping your legs together, lower them to one side until they are a few inches above the ground.",
      "Pause for a moment, then lift your legs back to the starting position.",
      "Repeat the movement to the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/cQNh7U0pvjJiDu",
    id: "0013",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/urNkDTzX8mn0k4",
    id: "0016",
    name: "assisted prone hamstring",
    target: "hamstrings",
    secondaryMuscles: ["glutes", "lower back"],
    instructions: [
      "Lie face down on a mat or bench with your legs fully extended.",
      "Have a partner or use a resistance band to secure your ankles.",
      "Engage your hamstrings and lift your legs towards your glutes, keeping your knees straight.",
      "Pause for a moment at the top, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/uSx1yVYBRT8xVd",
    id: "1713",
    name: "assisted prone lying quads stretch",
    target: "quads",
    secondaryMuscles: ["hamstrings", "glutes"],
    instructions: [
      "Lie face down on the ground with your legs extended.",
      "Bend your left knee and reach back with your left hand to grab your left foot or ankle.",
      "Gently pull your left foot towards your glutes, feeling a stretch in your left quad.",
      "Hold the stretch for 20-30 seconds, then release.",
      "Repeat with your right leg.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/axgjow8o1AowNZ",
    id: "1714",
    name: "assisted prone rectus femoris stretch",
    target: "abs",
    secondaryMuscles: ["quadriceps"],
    instructions: [
      "Lie face down on the ground with your legs straight.",
      "Bend your right knee and reach back with your right hand to grab your right foot or ankle.",
      "Gently pull your right foot or ankle towards your glutes, feeling a stretch in the front of your right thigh.",
      "Hold the stretch for 20-30 seconds.",
      "Release and repeat on the other side.",
    ],
  },
];
